spec: add CLI specs for notation list/login/logout/plugin
notaryproject/notation pull request #362
Opened 2022-09-28 09:08 UTC by yizha1

2022-09-29 05:43 UTC, binbin-li commented on specs/commandline/list.md
> +Use `notation list` to list all the signatures of the signing artifact.
question: should we say `signed artifact` or `signing artifact`?

2022-09-29 05:43 UTC, binbin-li commented on specs/commandline/list.md
> +notation list https://<registry>/<repository>:<tag>
do we need to specify `https://`?

2022-09-29 05:43 UTC, binbin-li commented on specs/commandline/list.md
> +Upon successful execution, the digests of signatures of signing container image are printed out.
same question, signed or signing.

2022-10-06 17:01 UTC, dtzar requested changes

2022-10-06 17:01 UTC, dtzar commented on specs/commandline/plugin.md
> +      --plain-http   Registry access via plain HTTP
Do we need this? If so - does it apply to plugins?

2022-10-06 17:01 UTC, dtzar commented on specs/commandline/plugin.md
> +Upon successful execution, a list of plugins are printed out with information of name, description, version, capabilities and errors. The capabilities show what the plugin is capable of, for example,
Suggest displaying a sample output from plugin ls.
`NAME       DESCRIPTION                                   VERSION                                                  CAPABILITIES            ERROR
azure-kv   Sign artifacts with keys in Azure Key Vault   0.3.0-alpha.1+79a19c8a85f95c3e88591ac1cfcec266c0008762   [SIGNATURE_GENERATOR]   <nil>`

2022-10-06 17:01 UTC, dtzar commented
Reviewed this as a group during community call today.  Once this feedback is addressed, we can merge.

2022-10-08 09:13 UTC, shizhMSFT commented on specs/commandline/list.md
> +  notation list <reference> [flags]
In Linux/Unix, `less` can be used for pagination (e.g. `notation list $ref | less`). Details of `less` can be found in `man less`.

Generally speaking, `less` will block the write pipeline and thus force `notation` stopping query the next link returned by the referrer API.

2022-10-10 07:58 UTC, yizha1 commented on specs/commandline/logout.md
> +  notation logout <server> [flags]
use `--all` flag to log out from all logged in registries.

2022-10-10 08:05 UTC, yizha1 commented on specs/commandline/list.md
> +  notation list <reference> [flags]
> IMO default behavior should be paginated as ORAS [referrers](https://github.com/oras-project/artifacts-spec/blob/main/manifest-referrers-api.md) API is paginated. Not having pagination will result in an unnecessary load on servers when 1st returned item in the list is what the user wanted. Also, it's usually good practice to have a paginated list API.

Maybe we can create another issue to address your comments. The implementation depends on the behavior of `oras-go` library. IMO, the current spec is good enough for rc.1 release.

2022-10-10 20:42 UTC, dtzar approved these changes

2022-10-12 01:15 UTC, priteshbandi commented on specs/commandline/plugin.md
> +Use `notation plugin` to manage the lifecycle of plugins. See notation [plugin documentation](https://github.com/notaryproject/notaryproject/blob/main/specs/plugin-extensibility.md) for more details.
```suggestion
Use `notation plugin` to manage plugins. See notation [plugin documentation](https://github.com/notaryproject/notaryproject/blob/main/specs/plugin-extensibility.md) for more details. The `notation plugin` command by itself performs no action. In order to operate on a plugin, one of the subcommands must be used.
```

2022-10-12 01:15 UTC, priteshbandi commented on specs/commandline/plugin.md
> +Manage the lifecycle of plugins
```suggestion
Manage the plugins
```

2022-10-12 01:15 UTC, priteshbandi commented on specs/commandline/plugin.md
> +Upon successful execution, a list of plugins are printed out with information of name, description, version, capabilities and errors. The capabilities show what the plugin is capable of, for example,
```suggestion
Upon successful execution, a list of plugins are printed out with information of name, description, version, capabilities and errors. The capabilities show what the plugin is capable of, for example, the plugin can generate signatures or verify signatures. The errors column indicates whether the plugin was installed properly or not, `<nil>` indicates that the plugin installed successfully.
```

2022-10-17 05:02 UTC, priteshbandi approved these changes
LGTM with one feedback

2022-10-17 05:02 UTC, priteshbandi commented on specs/commandline/list.md
> +    └──<digest_of_signature>
nit: Upon successful signature evaluation, we will short-circuit evaluation when we find verification succeeds for some signature

2022-10-17 22:44 UTC, vaninrao10 reviewed
For notation login and logout, do we also outline how to login into multiple registries and logout from multiple registries. We discussed in one of the community call.

2022-10-18 04:42 UTC, yizha1 commented
> For notation login and logout, do we also outline how to login into multiple registries and logout from multiple registries. We discussed in one of the community call.

Yes, I have added support for multiple login

2022-10-18 05:27 UTC, priteshbandi commented on specs/commandline/list.md
> +  notation list <reference> [flags]
Tacking it in https://github.com/notaryproject/notation/issues/403 for RC1

2022-10-18 07:18 UTC, FeynmanZhou approved these changes

2022-10-18 10:25 UTC, shizhMSFT commented on specs/commandline/logout.md
> +## Log out from all logged in registries
```suggestion
### Log out from all logged in registries
```

2022-10-18 12:29 UTC, shizhMSFT approved these changes
LGTM

2022-10-18 12:30 UTC, merged