update: updated notation verify command based on spec
notaryproject/notation pull request #418
Opened 2022-10-26 05:59 UTC by patrickzheng200

This PR updates notation verify command based on the [verify_spec](https://github.com/notaryproject/notation/blob/main/specs/commandline/verify.md).

Signed-off-by: Patrick Zheng <patrickzheng@microsoft.com>

2022-10-26 11:52 UTC, JeyJeyGao commented
LGTM

2022-10-27 02:36 UTC, JeyJeyGao approved these changes
LGTM

2022-10-27 14:06 UTC, shizhMSFT requested changes

2022-10-27 14:06 UTC, shizhMSFT commented on cmd/notation/verify.go
> +	command.Flags().StringVarP(&opts.pluginConfig, "plugin-config", "c", "", "{key}={value} pairs that are passed as is to a plugin, if the verification is associated with a verification plugin, refer p
`opts.pluginConfig` should be `[]string` instead of `string`.

2022-10-28 15:16 UTC, jondonas approved these changes
LGTM

2022-10-31 05:28 UTC, shizhMSFT approved these changes
LGTM with suggestions

2022-10-31 05:28 UTC, shizhMSFT commented on cmd/notation/verify.go
> +	command.Flags().StringArrayVarP(&opts.pluginConfig, "plugin-config", "c", []string{}, "{key}={value} pairs that are passed as it is to a plugin, if the verification is associated with a verification
nit:
```suggestion
	command.Flags().StringArrayVarP(&opts.pluginConfig, "plugin-config", "c", nil, "{key}={value} pairs that are passed as it is to a plugin, if the verification is associated with a verification plugin, refer plugin documentation to set appropriate values")
```

2022-10-31 05:28 UTC, shizhMSFT commented on internal/cmd/flags.go
> +		fs.StringArrayVarP(p, PflagPluginConfig.Name, PflagPluginConfig.Shorthand, []string{}, PflagPluginConfig.Usage)
nit:
```suggestion
		fs.StringArrayVarP(p, PflagPluginConfig.Name, PflagPluginConfig.Shorthand, nil, PflagPluginConfig.Usage)
```

2022-10-31 05:28 UTC, shizhMSFT commented on internal/cmd/flags.go
> +		index := strings.Index(pair, "=")
nit: Try [strings.Cut()](https://pkg.go.dev/strings#Cut).

2022-10-31 06:03 UTC, shizhMSFT approved these changes
LGTM

2022-10-31 06:03 UTC, merged