Add Yi Zha as notation maintainer
notaryproject/notation pull request #515
Opened 2023-01-26 22:47 UTC by lachie83

Add Yi Zha as a seed maintainer of Notation based on [their](https://github.com/notaryproject/notation/commits?author=yizha1) activity as per - https://github.com/notaryproject/notation/issues/514

Signed-off-by: Lachlan Evenson <lachlan.evenson@microsoft.com>

2023-01-27 00:53 UTC, sajayantony commented
LGTM but IANAM.

2023-01-27 19:03 UTC, priteshbandi commented
LGTM but again I am not a maintainer

2023-01-30 04:58 UTC, vaninrao10 commented
LGTM

2023-01-30 16:46 UTC, toddysm approved these changes
LGTM

2023-01-31 14:03 UTC, shizhMSFT approved these changes
LGTM

2023-02-02 20:33 UTC, SteveLasker requested changes
+1 to adding @yizha1 
Please see comments in https://github.com/notaryproject/notation/pull/530, https://github.com/notaryproject/notation/pull/531, https://github.com/notaryproject/notation/pull/532

2023-02-03 01:02 UTC, JeyJeyGao approved these changes
LGTM but IANAM

2023-02-03 01:03 UTC, patrickzheng200 approved these changes
LGTM but IANAM

2023-02-06 04:39 UTC, binbin-li approved these changes
LGTM but IANAM

2023-02-08 19:27 UTC, vaninrao10 approved these changes
LGTM but IANAM

2023-02-08 20:06 UTC, gokarnm commented
LGTM but IANAM

2023-02-14 21:51 UTC, priteshbandi approved these changes
LGTM but IANAM

2023-02-14 22:10 UTC, iamsamirzon approved these changes

2023-02-17 07:34 UTC, yizha1 commented
Close as aggregated PR https://github.com/notaryproject/notation/pull/542 was merged

2023-02-17 07:34 UTC, closed without merging