Add spec for verify json output
notaryproject/notation pull request #559
Opened 2023-02-16 21:59 UTC by byronchien

Adds spec for `notation verify $IMAGE --output json`.

Changes from previous iteration:
- adds a details field for additional information related to the result
- outputs a JSON object on failure and skipped results

Related issues and PRs:
- https://github.com/notaryproject/notation/pull/527
- https://github.com/notaryproject/notation/issues/546
- https://github.com/notaryproject/notation/issues/547

2023-06-13 01:03 UTC, FeynmanZhou commented
@byronchien  You may need to rebase your branch and sync with the upstream main as it has conflicts.

2023-06-13 21:59 UTC, priteshbandi commented on specs/commandline/verify.md
> +    },
Should we also add signature reference/digest? And move userMetadata to be a child of it?
```
{
    "reference": "localhost:5000/net-monitor@sha256:b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9",
    "signatures":  [
        {
            "digest": "sha256:73c803930ea3ba1e54bc25c2bdc53edd0284c62ed651fe7b00369da519a33",
            "userDefinedAttributes":  {
                "io.wabbit-networks.buildId": "123" 
            }
....
```

Also to be consistent with [inspect](https://github.com/notaryproject/notation/blob/main/specs/commandline/inspect.md#inspect-signatures-on-the-supplied-oci-artifact-with-an-example-of-json-output), should we rename `userMetadata` to `userDefinedAttributes`

2023-06-14 19:53 UTC, priteshbandi submitted a review, later dismissed
LGTM

2023-06-14 19:56 UTC, priteshbandi commented on specs/commandline/verify.md
> +```text
```suggestion
```json
```

2023-06-14 19:56 UTC, priteshbandi commented on specs/commandline/verify.md
> +```text
```suggestion
```json
```

2023-06-14 20:48 UTC, priteshbandi approved these changes
LGTM

2023-07-05 17:08 UTC, priteshbandi approved these changes
LGTM

2023-07-05 20:50 UTC, sajayantony commented
+1. I think it's worth merging this. Typically it would be good to call out all possible values of `result` if there are more.

2023-07-06 00:39 UTC, FeynmanZhou approved these changes
LGTM

2023-07-07 09:42 UTC, shizhMSFT commented
Should it be merged post v1?

2023-07-08 02:19 UTC, yizha1 commented
> Should it be merged post v1?

+1 on merging it post v1.

2023-07-11 02:11 UTC, Two-Hearts commented on specs/commandline/verify.md
> +Use the `--output` flag to format verification output in json.
Can you also add this new flag along with its description into the `Outline` session of this spec? (https://github.com/notaryproject/notation/blob/main/specs/commandline/verify.md#outline)

2023-07-11 02:11 UTC, Two-Hearts commented on specs/commandline/verify.md
> +notation verify --output json localhost:5000/net-monitor@sha256:b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9
Just curious, what error message are we expecting from the following command:
`notation verify --output <something_not_defined> localhost:5000/net-monitor@sha256:b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9`

2023-07-18 07:38 UTC, yizha1 requested changes
@byronchien I reviewed this PR again. Here are two comments:
- Unified solution for all Notation CLI commands: I couldn't recall any reason behind this PR that only verify command is addressed. The Json output should be considered for all other Notation CLI commands. So, it is suggested to create a unified solution for all Notation CLI commands.
- About the flag name `-o --output`: There is a new feature about signing and verifying arbitrary files. For this feature, we may need to output signature to a file during signing, there may be a conflict of using `--output`. It seems `notation inspect` command already uses the flag `--output`. We need to align the usage of flag `--output`.
/cc: @priteshbandi @shizhMSFT @FeynmanZhou

2024-04-23 01:46 UTC, closed without merging