add addon opa
notaryproject/notation pull request #62
Opened 2021-05-15 19:28 UTC by honeybadger10

2021-05-20 16:32 UTC, SteveLasker commented
Pinging @ritazh for :eyes:

2021-05-21 09:46 UTC, marcofranssen commented on addons/opa/README.md
> +openssl genrsa -out ca.key 2048
can we move this into a code block like

\`\`\`bash
openssl …………
\`\`\`

2021-05-21 09:58 UTC, marcofranssen requested changes
Some minor things captured by markdown linting.

Furthermore I think it would be great to template the k8s resources in a helm chart to have less manual setup steps and replacements in the k8s objects.

It is a good practice to put helm charts in a `charts` folder in the root of the repository.

See here some examples.

https://github.com/philips-labs/helm-charts

See here an example outline to have a quickstart.

```bash
tree charts
charts
└── opa
    ├── Chart.yaml
    ├── LICENSE
    ├── templates
    │   ├── NOTES.txt
    │   ├── _helpers.tpl
    │   ├── admission-controller-configmap.yaml
    │   ├── admission-controller-deployment.yaml
    │   └── admission-controller-service.yaml
    └── values.yaml

2 directories, 8 files
```

You can create this using `helm create` 

```bash
helm create --help

This command creates a chart directory along with the common files and
directories used in a chart.

For example, 'helm create foo' will create a directory structure that looks
something like this:

    foo/
    ├── .helmignore   # Contains patterns to ignore when packaging Helm charts.
    ├── Chart.yaml    # Information about your chart
    ├── values.yaml   # The default values for your templates
    ├── charts/       # Charts that this chart depends on
    └── templates/    # The template files
        └── tests/    # The test files
```

2021-05-21 09:58 UTC, marcofranssen commented on addons/opa/README.md
> +## denied deployment
```suggestion
## denied deployment

```

2021-05-21 09:58 UTC, marcofranssen commented on addons/opa/README.md
> +## allowed deployment
```suggestion
## allowed deployment

```

2021-05-21 09:58 UTC, marcofranssen commented on addons/opa/README.md
> +## install OPA
```suggestion
## install OPA

```

2021-06-04 22:34 UTC, ritazh commented on addons/opa/rego/nv2.rego
> +## tbd: how to load certs
Is there a missing step here?

2021-06-04 23:40 UTC, ritazh commented on addons/opa/rego/nv2.rego
> +  response_signature := http.send({"method": "get", "url": url_digest, "headers": headers_json, "tls_insecure_skip_verify": true})
can you give an example of an url that returns a signature?

2021-06-05 00:03 UTC, sozercan commented
does this work with private registries?

2021-06-05 00:10 UTC, ritazh commented
In general, it would be helpful to include instructions for:
- prerequisites for which registry supports this feature and how to enable the feature on the registry
- setting up nv2

2021-06-05 00:33 UTC, SteveLasker commented
> does this work with private registries? or public ones that requires tokens?

Oh, that's a good point. CNCF distribution doesn't have auth, but any cloud deployment would need to validate with an authenticated connection to the registry. Most cloud providers would have a Service Identity like configuration, so I'm not sure how that associates with OPA/Gatekeeper as customers are really trying to move away from any secrets model as it complicates key rotation.

2021-06-05 00:34 UTC, SteveLasker commented
> In general, it would be helpful to include instructions for:
> * prerequisites for which registry supports this feature and how to enable the feature on the registry

At this point, nobody supports it as we're still incubating the idea, so only a local instance of CNCF distribution will work. 
Fall 2021, that's another story :)

2021-07-06 22:32 UTC, SteveLasker commented
Adding @mnltejaswini ^

2021-08-30 18:17 UTC, SteveLasker commented
@honeybadger10, just a ping. We haven't forgotten about this. There's some work happening to enable data providers to enable the passthrough of data within OPA to enable the flows.  
We should be able to pop this up again soon.

2022-07-20 17:57 UTC, dtzar commented
@honeybadger10 - thank you for your PR.  It's been inactive for a long time and we want to avoid specific implementations which utilize notation in this repository, so I'm closing it out.  Perhaps you could put something into your own repository?

For instance, we have [ratify](https://github.com/deislabs/ratify) which utilizes notation v2 with gatekeeper and there are others like [connaisseur](https://github.com/sse-secure-systems/connaisseur) - currently only supports notary v1.

2022-07-20 17:57 UTC, closed without merging